'use strict'
const paparam = require('paparam')
const { header, footer, command, flag, arg, summary, description, bail, rest, validate } = paparam
const { usage, print, isTTY } = require('../lib/terminal.js')
const { cmdArgs } = require('../argv')
const errors = require('pear-errors')
const { definition } = require('../lib/cmd')
const { UPGRADE, PEAR_DEV_ROOT } = require('../constants.js')
const { runMenu } = require('bare-tui-paparam')
const H = require('./hints.js')

const commands = {
  touch: require('./touch'),
  stage: require('./stage'),
  build: require('pear-build'),
  seed: require('./seed'),
  provision: require('./provision'),
  multisig: require('./multisig'),
  info: require('./info'),
  dump: require('./dump'),
  install: require('pear-install/cmd').runner,
  data: require('./data'),
  changelog: require('./changelog'),
  sidecar: require('./sidecar'),
  gc: require('./gc'),
  cores: require('./cores'),
  blindRelay: require('./blind-relay'),
  versions: require('./versions')
}

module.exports = async (ipc, argv = cmdArgs) => {
  await ipc.ready()

  Bare.prependListener('exit', () => {
    ipc.close()
  })

  const touch = command(
    'touch',
    summary('Generate a project link'),
    description`Create a new randomly generated Pear link`,
    flag('--json', 'Newline delimited JSON output'),
    flag('--vanity <vanity>', 'Generate a link starting with this z32 prefix').hint(
      H.touch.vanity.text
    ),
    commands.touch
  )

  const seed = command(
    'seed',
    summary('Seed or reseed a project'),
    description`
      Announce a project link on the network and serve its blocks to peers. 

      Runs until you exit, or until every --until-sync peer has fully synced.
    `,
    arg('<link>', 'Pear link to seed').hint(H.seed.link.text),
    flag('--no-tty', 'Print plain log lines instead of the live terminal UI').hint(
      H.seed.noTty.text
    ),
    flag(
      '--until-sync <key>',
      'Exit once this peer has synced. Pass multiple flags to wait for more peers'
    )
      .multiple()
      .hint(H.seed.untilSync.text),
    flag('--stats-interval <milliseconds>', 'Stats refresh interval in milliseconds').hint(
      H.seed.statsInterval.text
    ),
    flag('--json', 'Newline delimited JSON output'),
    commands.seed
  )

  const build = command('build', require('pear-build/package.json').command, async (cmd) => {
    const builder = commands.build(cmd.flags)
    builder.on('error', () => {})
    await builder.done()
  })

  const stage = command(
    'stage',
    summary('Sync disk changes into project'),
    description`
      Stage local changes to a project link. 

      Outputs diff information and the resulting project link.
    `,
    arg('<link>', 'Pear link to stage').hint(H.stage.link.text),
    arg('[dir=.]', 'Project directory to stage from').hint(H.stage.dir.text),
    flag('--dry-run|-d', 'Execute a stage without writing').hint(H.stage.dryRun.text),
    flag('--ignore <paths>', "Don't stage these comma-separated paths").hint(H.stage.ignore.text),
    flag('--purge', 'Also delete already-staged files that now match the ignore list').hint(
      H.stage.purge.text
    ),
    flag('--only <paths>', 'Only stage these comma-separated paths').hint(H.stage.only.text),
    flag(
      '--truncate <n>',
      'Advanced. Truncate the project to this version length. Destructive — later versions are dropped'
    ).hint(H.stage.truncate.text),
    flag('--json', 'Newline delimited JSON output'),
    commands.stage
  )

  const provision = command(
    'provision',
    summary('Block-sync source & production'),
    description`
      Synchronize blocks from a source link to a pre-production target link. 

      The target can then be multisig'd against a production link. 

      Use pear touch to generate the target link first.
    `,
    arg('<source-verlink>', 'Versioned source link').hint(H.provision.sourceVerlink.text),
    arg('<target-link>', 'Target link to sync to, as generated by pear touch').hint(
      H.provision.targetLink.text
    ),
    arg('<production-verlink>', 'Versioned production link to sync against').hint(
      H.provision.productionVerlink.text
    ),
    flag('--dry-run|-d', 'Execute provision to a disposable target').hint(H.provision.dryRun.text),
    flag('--json', 'Newline delimited JSON output'),
    commands.provision
  )

  const multisig = command(
    'multisig',
    summary('Production signing coordination'),
    description`
      Quorum-based cryptographic cosigning for production releases. 

      Gather enough signatures to approve a release to synchronize 
      onto a production link. 

      Example - 2/3 must sign to approve 
      pear.json: { 
        "multisig": { 
          "publicKeys": ["<pubkey1>", "<pubkey2>", "<pubkey3>"], 
          "namespace": "my-org/my-app", 
          "quorum": 2 
        } 
      }
    `,
    command(
      'keys',
      summary('Manage signing keys'),
      command(
        'get',
        summary('Get signing key, initializing if needed'),
        description`
          Idempotent. 

          Creates a public/private keypair if one doesn't already exist. 

          Always prints the public key.
        `,
        arg(
          '[name=default]',
          'Key identifier for the keypair\'s on-disk names. Defaults to "default"'
        ).hint(H.multisig.keysGet.name.text),
        flag('--secret', 'Also print the private key').hint(H.multisig.keysGet.secret.text),
        flag('--json', 'Newline delimited JSON output'),
        commands.multisig
      ),
      command(
        'paths',
        summary('Print paths to public & private key files'),
        arg(
          '[name=default]',
          'Key identifier for the keypair\'s on-disk names. Defaults to "default"'
        ).hint(H.multisig.keysPaths.name.text),
        flag('--json', 'Newline delimited JSON output'),
        commands.multisig
      ),
      command(
        'list',
        summary('List signing keys'),
        description`
          Output all names and public keys
        `,
        flag('--json', 'Newline delimited JSON output'),
        commands.multisig
      ),
      command(
        'add',
        summary('Add signing keys'),
        description`
          Import a signing keypair or add a known public key
        `,
        arg('<name>', 'Name to store this key under. Must not already exist').hint(
          H.multisig.keysAdd.name.text
        ),
        arg('<public-key>', 'Public key — a key path or key string').hint(
          H.multisig.keysAdd.publicKey.text
        ),
        arg(
          '[private-key]',
          'Private key — a key path or key string. Omit for public-key only'
        ).hint(H.multisig.keysAdd.privateKey.text),
        flag('--json', 'Newline delimited JSON output'),
        commands.multisig
      ),
      command(
        'remove',
        summary('Remove signing keys'),
        arg('<name>', 'Name of the key to remove').hint(H.multisig.keysRemove.name.text),
        flag('--json', 'Newline delimited JSON output'),
        commands.multisig
      ),
      (cmd) => console.log(cmd.command.help())
    ),
    command(
      'link',
      summary('Print project multisig link'),
      description`
        The multisig link is derived from the publicKeys, quorum and 
        namespace fields of your project's pear.json. 

        Run pear help multisig for an example config.
      `,
      flag(
        '--config [./pear.json]',
        "Path to the project's pear.json. Defaults to ./pear.json"
      ).hint(H.multisig.link.config.text),
      flag('--vanity <vanity>', 'Generate a link starting with this z32 prefix').hint(
        H.multisig.link.vanity.text
      ),
      flag('--json', 'Newline delimited JSON output'),
      commands.multisig
    ),
    command(
      'request',
      summary('Create a multisig request'),
      description`
        Create a signing request to synchronize a versioned source link 
        onto the project's multisig link, as printed by pear multisig link.
      `,
      flag('--force', 'Skip sanity checks').hint(H.multisig.request.force.text),
      flag(
        '--config [./pear.json]',
        "Path to the project's pear.json. Defaults to ./pear.json"
      ).hint(H.multisig.request.config.text),
      flag(
        '--peer-update-timeout <milliseconds>',
        'How long to wait for peers to update, in milliseconds'
      ).hint(H.multisig.request.peerUpdateTimeout.text),
      flag('--json', 'Newline delimited JSON output'),
      arg('<verlink>', 'Versioned source link to sign off').hint(H.multisig.request.verlink.text),
      commands.multisig
    ),
    command(
      'sign',
      summary('Sign a multisig request'),
      description`
        Sign a multisig request using a local signing key. 

        The key's public counterpart must be listed in the 
        multisig.publicKeys field of the pear.json at the source link 
        supplied to pear multisig request.
      `,
      arg('<request>', 'As returned by pear multisig request').hint(H.multisig.sign.request.text),
      arg('[name=default]', 'Local key to sign with, by name. Defaults to "default"').hint(
        H.multisig.sign.name.text
      ),
      flag('--json', 'Newline delimited JSON output'),
      commands.multisig
    ),
    command(
      'verify',
      summary('Verify multisig request & responses'),
      description('Verify inputs and perform a commit dry run'),
      flag('--force-dangerous', 'Advanced. Careful, this may break the core').hide(),
      flag(
        '--config [./pear.json]',
        "Path to the project's pear.json. Defaults to ./pear.json"
      ).hint(H.multisig.verify.config.text),
      flag(
        '--peer-update-timeout <milliseconds>',
        'How long to wait for peers to update, in milliseconds'
      ).hint(H.multisig.verify.peerUpdateTimeout.text),
      flag('--json', 'Newline delimited JSON output'),
      arg('<source-link>', 'Source Pear link').hint(H.multisig.verify.sourceLink.text),
      arg('<request>', 'Signing request, as printed by pear multisig request').hint(
        H.multisig.verify.request.text
      ),
      rest('[...responses]', 'Signing responses, as printed by pear multisig sign').hint(
        H.multisig.verify.responses.text
      ),
      commands.multisig
    ),
    command(
      'commit',
      summary('Commit multisig to go live'),
      description('Apply signatures to allow sync from source drive to multisig drive'),
      flag(
        '--config [./pear.json]',
        "Path to the project's pear.json. Defaults to ./pear.json"
      ).hint(H.multisig.commit.config.text),
      flag('--force-dangerous', 'Advanced. Careful, this may break the core').hide(),
      flag(
        '--peer-update-timeout <milliseconds>',
        'How long to wait for peers to update, in milliseconds'
      ).hint(H.multisig.commit.peerUpdateTimeout.text),
      flag('--json', 'Newline delimited JSON output'),
      arg('<source-link>', 'Source Pear link').hint(H.multisig.commit.sourceLink.text),
      arg('<request>', 'Signing request, as printed by pear multisig request').hint(
        H.multisig.commit.request.text
      ),
      rest('[...responses]', 'Signing responses, as printed by pear multisig sign').hint(
        H.multisig.commit.responses.text
      ),
      commands.multisig
    ),
    (cmd) => console.log(cmd.command.help())
  )

  const info = command(
    'info',
    summary('View project information'),
    description`
      View information about a project. 

      Supply a link to inspect a specific project, or omit it to view 
      platform information.
    `,
    arg('[link]', 'Project to view info for').hint(H.info.link.text),
    arg('[dir=.]', 'Project directory path').hint(H.info.dir.text),
    flag('--changelog', 'View changelog only').hide(),
    flag('--full-changelog', 'Full record of changes').hide(),
    flag('--changelog-max <n>', 'Maximum changelog entries').hide(),
    flag('--metadata', 'Print the project metadata').hint(H.info.metadata.text),
    flag('--manifest', 'Print the app manifest').hint(H.info.manifest.text),
    flag('--multisig', 'Print the multisig quorum and signing keys').hint(H.info.multisig.text),
    flag('--key', 'Print the view key').hint(H.info.key.text),
    flag('--json', 'Newline delimited JSON output'),
    commands.info
  )

  const dump = command(
    'dump',
    summary('Synchronize files from a link to a directory'),
    arg('<link>', 'Link to dump from. May be file:, pear: or dir').hint(H.dump.link.text),
    arg('[dir]', 'Directory path to dump to. Use - for output-only').hint(H.dump.dir.text),
    flag('--dry-run|-d', 'Preview without writing any changes').hint(H.dump.dryRun.text),
    flag('--checkout <n>', 'Dump the project as it was at this version length').hint(
      H.dump.checkout.text
    ),
    flag('--only <paths>', 'Only dump these comma-separated paths').hint(H.dump.only.text),
    flag('--force|-f', 'Force overwrite existing files').hint(H.dump.force.text),
    flag('--list', 'List the paths inside the link instead of writing any files').hint(
      H.dump.list.text
    ),
    flag('--no-prune', 'Keep destination files that are missing from the source').hint(
      H.dump.noPrune.text
    ),
    flag('--json', 'Newline delimited JSON output'),
    validate((cmd) => {
      if (cmd.flags.list) cmd.args.dir = '-'
      return true
    }),
    validate('<dir> is required', (cmd) => !!cmd.args.dir),
    commands.dump
  )

  const install = command(
    'install',
    arg('<link>', 'Pear link origin to install from').hint(H.install.link.text),
    require('pear-install/package.json').command,
    commands.install
  )

  const data = command(
    'data',
    summary('Explore platform database'),
    command('dht', summary('DHT known-nodes cache'), commands.data).hint(H.data.dht.text),
    command('multisig', summary('Multisig records'), commands.data),
    flag('--json', 'Newline delimited JSON output'),
    (cmd) => {
      console.log(cmd.command.help())
    }
  )

  const changelog = command(
    'changelog',
    summary('View project changelog'),
    description`
      View a project's changelog. 

      Supply a link to inspect a specific project, or omit it to view 
      Pear's own changelog.
    `,
    arg('[link]', 'Project to view changelog of').hint(H.changelog.link.text),
    flag('--max|-m <n=10>', 'Maximum number of entries to show').hint(H.changelog.max.text),
    flag(
      '--of <semver=^*>',
      'Only show entries matching this semver range. Default: latest major'
    ).hint(H.changelog.of.text),
    flag('--full', 'Show entire changelog').hint(H.changelog.full.text),
    flag('--json', 'Newline delimited JSON output'),
    commands.changelog
  )

  const sidecar = command(
    'sidecar',
    command('shutdown', commands.sidecar, summary('Shutdown running sidecar')),
    command('inspect', commands.sidecar, summary('Enable running sidecar inspector')).hint(
      H.sidecar.inspect.text
    ),
    summary('Advanced. Run sidecar in terminal'),
    description`
      The sidecar is a local IPC server that brokers corestore access 
      for every running Pear app. 

      Running pear sidecar shuts down any existing sidecar and takes 
      over as the new one, staying attached to this terminal.
    `,
    flag('--log-level <level>', 'Verbosity to log at — 0=off, 1=error, 2=info, or 3=trace').hint(
      H.sidecar.logLevel.text
    ),
    flag('--dht-bootstrap <nodes>').hide(),
    commands.sidecar
  )

  const gc = command(
    'gc',
    summary('Advanced. Clear dangling resources'),
    command(
      'cores',
      summary('Clear corestore cores'),
      flag('--force|-f', 'Clear writable cores without confirmation').hint(H.gc.cores.force.text),
      arg('<link|name>', 'Clear the cores belonging to this link or app name').hint(
        H.gc.cores.linkOrName.text
      ),
      commands.gc
    ).hint(H.gc.cores.$.text),
    flag('--json', 'Newline delimited JSON output'),
    () => {
      console.log(gc.help())
    }
  )

  const cores = command(
    'cores',
    summary('List platform cores'),
    description`
      Lists the cores in the platform corestore. 
      Empty cores are omitted unless --all-cores is set.
    `,
    flag('--all-cores', 'List all cores, including empty cores').hint(H.cores.allCores.text),
    flag('--json', 'Newline delimited JSON output'),
    commands.cores
  )

  const blindRelay = command(
    'blind-relay',
    summary('Run a blind relay for peers that cannot hole-punch'),
    command(
      'start',
      summary('Start the blind relay'),
      flag('--no-tty', 'Print plain log lines instead of the live terminal UI').hint(
        H.blindRelay.start.noTty.text
      ),
      flag('--stats-interval <milliseconds>', 'Stats refresh interval in milliseconds').hint(
        H.blindRelay.start.statsInterval.text
      ),
      flag('--json', 'Newline delimited JSON output'),
      commands.blindRelay
    ),
    () => {
      console.log(blindRelay.help())
    }
  )

  const versions = command(
    'versions',
    summary('View dependency versions'),
    flag('--modules|-m', 'Include module versions').hint(H.versions.modules.text),
    flag('--json', 'Newline delimited JSON output'),
    commands.versions
  )

  const help = command(
    'help',
    arg('[command]', 'Command to show help for. Omit to show the full overview').hint(
      H.help.command.text
    ),
    summary('View help for command'),
    (h) => {
      if (h.args.command) console.log(cmd.help(h.args.command))
      else console.log(cmd.overview({ full: true }))
    }
  )

  const cmd = command(
    'pear',
    ...definition,
    header(usage.header),
    touch,
    seed,
    stage,
    build,
    provision,
    multisig,
    info,
    dump,
    install,
    data,
    changelog,
    sidecar,
    gc,
    cores,
    blindRelay,
    versions,
    help,
    footer(usage.footer),
    bail(function explain(bail = {}) {
      if (!bail.reason && bail.err) {
        const known = errors.known()
        if (known.includes(bail.err.code) === false) {
          print(
            errors.ERR_UNKNOWN(
              'Unknown [ code: ' + (bail.err.code || '(none)') + ' ] ' + bail.err.stack
            ),
            false
          )
          Bare.exit(1)
        }
      }
      const messageUsage = (bail) => bail.err.message
      const messageOnly = (bail) => bail.err.message
      const opFail = (cmd) => cmd.err.info.message
      const codemap = new Map([
        ['UNKNOWN_FLAG', (bail) => 'Unrecognized Flag: --' + bail.flag.name],
        [
          'UNKNOWN_ARG',
          (bail) =>
            'Unrecognized Argument at index ' + bail.arg.index + ' with value ' + bail.arg.value
        ],
        ['MISSING_ARG', (bail) => bail.arg.value],
        ['INVALID', messageUsage],
        ['ERR_INVALID_INPUT', messageUsage],
        ['ERR_LEGACY', messageOnly],
        ['ERR_INVALID_TEMPLATE', messageOnly],
        ['ERR_INVALID_PROJECT_DIR', messageOnly],
        ['ERR_DIR_NONEMPTY', messageOnly],
        ['ERR_NOT_FOUND', messageOnly],
        ['ERR_OPERATION_FAILED', opFail]
      ])
      const nouse = [messageOnly, opFail]
      const subcode = bail.err?.code === 'ERR_OPERATION_FAILED' ? bail.err?.info?.code : null
      const code = codemap.has(subcode ?? bail.err?.code) ? (subcode ?? bail.err.code) : bail.reason
      const ref = codemap.get(code)
      let reason = bail.reason
      if (codemap.has(code)) {
        reason = subcode ? bail.err?.info?.message : (codemap.get(code)(bail) ?? bail.reason)
      }
      Bare.exitCode = 1

      if (argv.includes('--json')) {
        console.log(
          JSON.stringify({
            cmd: argv[0],
            tag: 'error',
            data: {
              success: false,
              code,
              message: reason
            }
          })
        )
        return
      }

      print(reason, false)

      if (nouse.some((fn) => fn === ref) || codemap.has(code) === false) return

      print('\n' + bail.command.usage())
    }),
    pear
  )

  async function pear({ flags }) {
    if (flags.v) {
      const pkg = require('../package.json')
      const { version } = pkg
      const devRoot = PEAR_DEV_ROOT
      const vinfo = await ipc.versions()
      const key = vinfo?.platform?.key || UPGRADE
      const fork = devRoot ? null : (vinfo?.platform?.fork ?? null)
      const length = devRoot ? null : (vinfo?.platform?.length ?? null)
      const hasVersioned = fork !== null && length !== null
      const versionedKey = hasVersioned ? `pear://${fork}.${length}.${stripPearPrefix(key)}` : key
      if (flags.json) {
        console.log(
          JSON.stringify({ key, version, path: devRoot, fork: fork, length, versionedKey })
        )
        return
      }
      console.log(versionedKey + ' / v' + version + '\n')

      if (devRoot) console.log('Path=' + devRoot)
      else console.log('Key=' + key)
      console.log('SemVer=' + version)
      if (fork !== null) console.log('Fork=' + fork)
      if (length !== null) console.log('Length=' + length)
      return
    }
    console.log(cmd.overview())
  }

  function stripPearPrefix(link) {
    if (typeof link !== 'string') return ''
    return link.startsWith('pear://') ? link.slice('pear://'.length) : link
  }

  const shell = require('../lib/cmd').command(argv)
  const cmdIx = shell?.indices.args.cmd ?? -1

  let program = null

  if (shell?.flags?.menu) {
    if (!isTTY) {
      print('pear --menu requires an interactive terminal', false)
      Bare.exitCode = 1
      ipc.close()
      return null
    }
    const confirmed = await runMenu(cmd, {
      onComplete: (result, { argv: menuArgv }) => {
        program = cmd.parse(menuArgv)
      }
    })
    if (!confirmed || !confirmed.run) {
      ipc.close()
      return null
    }
  } else {
    if (cmdIx > -1) argv = argv.slice(cmdIx)

    if (argv[0] === 'run') {
      const message =
        'pear run has been removed.\nUse the pear-runtime module instead: https://www.npmjs.com/package/pear-runtime'
      print(message, false)
      Bare.exitCode = 1
      ipc.close()
      return null
    }

    program = cmd.parse(argv)
  }

  if (program === null) {
    ipc.close()
    return null
  }

  if (program.running) {
    program.running.finally(() => {
      ipc.close()
    })
  }

  return program
}
